spring.application.name=ecomApp 

# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomdb
spring.datasource.username=postgres
spring.datasource.password=Admin1
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# Server
# ===============================
server.port=8081

# ===============================
# Security
# ===============================
# DO NOT disable Security Auto Configuration (needed for HttpSecurity)
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.debug=true
# JWT Secret (use a strong secret in prod)
jwt.secret=MySuperSecretKeyForJwt123!
jwt.expiration=3600000   # 1 hour in ms




